version: '2'
services:
    visitors-app:
        image: 10.120.13.75:45000/visitors
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://visitors-postgresql:5432/visitors
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    visitors-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=visitors
            - POSTGRES_PASSWORD=password
